spring.application.name=API


spring.datasource.url=jdbc:mysql://localhost:3307/infra_link_dataBase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret = yO3isl5T^Uo&tdlfDwhvF#-v?SXF*pMO^OiMFO31cB^vIRk$)o#O{Epj6Tcd&i+$W%+IkYES]nBN^6*@hPuUgX-Ao}]ruYiLWEY3pfoYOtEPZmEIpV[#oh>xP*}*{O=ETr(QRD$_b_a)P2mAM-J[jdTVZyb3mN#nww{SkPUcpEh0jvfh+2v8(RWka}F6&acsljszO8ISJ{y]!aZ(9+{uv03N+}IrBZ^yUK!]S]2X3MHqJa{gA1*$i^[E8fOToL7+pWr!ZR]K9aS*%{5#EKDb(G8%$q43t{umM4*K7gzc!DRI




